version: 2


# Defining run components
path-run: &update-path
  name: Update PATH and devine env var at runtime
  command: |
    echo 'export PATH=/home/circleci/.local/bin:$PATH' >> $BASH_ENV
    source $BASH_ENV

pip-run: &pip-install
  name: Upgrade pip, setuptools, wheel
  command: |
    python -mpip install --upgrade --user pip
    python -mpip install --upgrade --user wheel
    python -mpip install --upgrade --user setuptools

sphinx-run: &sphinx-install
  name: Pip install sphinx and reqs
  command: |
    python -mpip install --user sphinx
    python -mpip install --user nbsphinx
    python -mpip install --user sphinx_rtd_theme
    python -mpip install --user ghp-import 

testenv-run: &testenv-install
  name: Install Test Prereqs
  command: |
    python -mpip install --user cookiecutter
    python -mpip install --user pytest
    python -mpip install --user pytest-cookies
    python -mpip install --user tox

test-run: &test-run
  name: Run unit tests
  command: |
    pytest


docs-run: &build-docs
  name: Render the docs
  command: |
      cookiecutter . --no-input
      cd docs
      make html

publish-run: &publish-docs
  name: Publish to GH-pages
  command: |
    ghp-import -n -m "Published from CircleCI [ci skip]" -b gh-pages docs/_build/html
    git push -u origin gh-pages


# Actually orchestrate the work
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: *update-path
      - run: *pip-install
      - run: *sphinx-install
      - run: *testenv-install
      - run: *test-run
      - run: *build-docs
  deploy:
    branch: master
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: *update-path
      - run: *pip-install
      - run: *sphinx-install
      - run: *testenv-install
      - run: *test-run
      - run: *build-docs
      - run: *publish-docs

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
